In [1]:
battery_data = [  (0, 32, 400, 20, 95),
                  (1, 35, 395, 22, 88),
                  (2, 38, 390, 25, 80),
                  (3, 40, 385, 28, 70),
                  (4, 42, 380, 30, 60),
                  (5, 45, 375, 32, 48) ]
print("Time Temperature Voltage Current Charge")
for reading in battery_data:
   print(reading)

Time Temperature Voltage Current Charge
(0, 32, 400, 20, 95)
(1, 35, 395, 22, 88)
(2, 38, 390, 25, 80)
(3, 40, 385, 28, 70)
(4, 42, 380, 30, 60)
(5, 45, 375, 32, 48)


In [4]:
for reading in battery_data:
   temperature = reading[1]
   if temperature > 40:
    print(f"Time {reading[0]}: High Temperature Alert")
   else:
     print(f"Time {reading[0]}: Temperature Normal")

Time 0: Temperature Normal
Time 1: Temperature Normal
Time 2: Temperature Normal
Time 3: Temperature Normal
Time 4: High Temperature Alert
Time 5: High Temperature Alert


In [6]:
for reading in battery_data:
   charge = reading[4]
   if charge < 50:
    print(f"Time {reading[0]}: Low Battery Alert")
   else:
    print(f"Time {reading[0]}: Battery Charge Normal")

Time 0: Battery Charge Normal
Time 1: Battery Charge Normal
Time 2: Battery Charge Normal
Time 3: Battery Charge Normal
Time 4: Battery Charge Normal
Time 5: Low Battery Alert


In [7]:
def battery_status(charge):
  if charge > 70:
     return "High"
  elif 50 <= charge <= 70:
    return "Medium"
  else:
    return "Low"
for reading in battery_data:
      charge = reading[4]
      print(f"Charge: {charge}% -> {battery_status(charge)}")

Charge: 95% -> High
Charge: 88% -> High
Charge: 80% -> High
Charge: 70% -> Medium
Charge: 60% -> Medium
Charge: 48% -> Low


In [8]:
import numpy as np
D= np.array([  [32, 400, 20, 95],
                 [35, 395, 22, 88],
                 [38, 390, 25, 80],
                 [40, 385, 28, 70],
                 [42, 380, 30, 60],
                 [45, 375, 32, 48] ])
print(D)

[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]


In [9]:
print(D.shape)

(6, 4)


In [12]:
averages = np.mean(D, axis=0)

print("Average Temperature:", averages[0])
print("Average Voltage:", averages[1])
print("Average Current:", averages[2])
print("Average Charge:", averages[3])

Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5


In [13]:
max_temperature = np.max(D[:, 0])
min_temperature = np.min(D[:, 0])
print("Maximum Temperature:", max_temperature)
print("Minimum Temperature:", min_temperature)

Maximum Temperature: 45
Minimum Temperature: 32


In [14]:
voltage = D[:, 1]
print(voltage)

[400 395 390 385 380 375]


In [15]:
high_temperature = D[D[:, 0] > 40]
print(high_temperature)

[[ 42 380  30  60]
 [ 45 375  32  48]]


In [16]:
low_battery = D[D[:, 3] < 50]
print(low_battery)

[[ 45 375  32  48]]


In [17]:
import numpy as np
A = np.array([ [2, 1], [1, 3] ])
X = np.array([ [40], [25] ])
Y = A @ X
print(Y)

[[105]
 [115]]


In [18]:
print(A.T)

[[2 1]
 [1 3]]


In [19]:
det_A = np.linalg.det(A)
print(det_A)

5.000000000000001


In [20]:
A = np.array([ [2, 1], [1, 3] ])
B = np.array([ 100, 120 ])
solution = np.linalg.solve(A, B)
print(solution)

[36. 28.]


In [21]:
def discharge_rate(t):
  return -2 - t
print("Rate at t=2:", discharge_rate(2), "%/hour")
print("Rate at t=5:", discharge_rate(5), "%/hour")

Rate at t=2: -4 %/hour
Rate at t=5: -7 %/hour
